import { TOOL_NAME, TOOL_VERSION, SCHEMA_VERSION } from '@/core';
import type { AuthFlow, CookieDiff, StorageDiff } from '@/core';
import { generateMermaidDiagram } from './mermaid.js';

export type MarkdownOptions = {
  /** raw 민감 정보를 포함할지 여부. 기본 false. */
  includeRaw?: boolean;
  /** 헤더에 raw 토큰을 절대 포함하지 않음 (강제). */
  enforceMasking?: boolean;
};

export function generateMarkdownReport(
  flow: AuthFlow,
  cookieDiff: CookieDiff,
  storageDiff: StorageDiff,
  opts: MarkdownOptions = {},
): string {
  const out: string[] = [];
  out.push(`# ${TOOL_NAME} Report`);
  out.push('');
  out.push(
    `> Generated by ${TOOL_NAME} v${TOOL_VERSION} (schema ${SCHEMA_VERSION}). ` +
      `Sensitive values are masked by default.`,
  );
  out.push('');

  // Summary
  out.push('## Summary');
  out.push('');
  out.push(`- **Target URL:** ${flow.targetUrl}`);
  out.push(`- **Started:** ${flow.startedAt}`);
  if (flow.endedAt) out.push(`- **Ended:** ${flow.endedAt}`);
  out.push(`- **Requests captured:** ${flow.requests.length}`);
  out.push(`- **Login candidates:** ${flow.loginCandidates.length}`);
  out.push('');

  // Auth Type
  out.push('## Detected Authentication Type');
  out.push('');
  if (flow.summary) {
    out.push(
      `- **Auth Type:** \`${flow.summary.authType}\` (confidence: ${flow.summary.confidence.toFixed(0)} – ${flow.summary.confidenceLevel})`,
    );
    if (flow.summary.detectedSignals.length > 0) {
      out.push('');
      out.push('**Signals:**');
      out.push('');
      for (const s of flow.summary.detectedSignals) {
        out.push(`- [+${s.weight}] ${s.description}`);
      }
    }
  } else {
    out.push('No summary available.');
  }
  out.push('');

  // Login Candidate
  out.push('## Login Request Candidate');
  out.push('');
  const top = flow.loginCandidates[0];
  if (top) {
    const req = flow.requests.find((r) => r.id === top.requestId);
    out.push(`- **Score:** ${top.score} (${top.confidence})`);
    if (req) {
      out.push(`- **Method/URL:** \`${req.method.toUpperCase()} ${req.url}\``);
    }
    out.push('');
    out.push('**Reasons:**');
    out.push('');
    for (const r of top.reasons) {
      out.push(`- ${r}`);
    }
  } else {
    out.push('No clear authentication request was detected.');
    out.push('You can manually select a request from the timeline.');
  }
  out.push('');

  // Cookie Changes
  out.push('## Cookie Changes');
  out.push('');
  if (
    cookieDiff.added.length === 0 &&
    cookieDiff.removed.length === 0 &&
    cookieDiff.changed.length === 0
  ) {
    out.push('No cookie changes were detected during this capture.');
  } else {
    if (cookieDiff.added.length > 0) {
      out.push('**Added:**');
      out.push('');
      for (const c of cookieDiff.added) {
        out.push(
          `- \`${c.name}\` @ ${c.domain}${c.path} → ${cookieValueDisplay(c.value, opts)} ${flagSuffix(c)}`,
        );
      }
      out.push('');
    }
    if (cookieDiff.changed.length > 0) {
      out.push('**Changed:**');
      out.push('');
      for (const c of cookieDiff.changed) {
        out.push(
          `- \`${c.after.name}\` @ ${c.after.domain}${c.after.path}: ${cookieValueDisplay(c.before.value, opts)} → ${cookieValueDisplay(c.after.value, opts)}`,
        );
      }
      out.push('');
    }
    if (cookieDiff.removed.length > 0) {
      out.push('**Removed:**');
      out.push('');
      for (const c of cookieDiff.removed) {
        out.push(`- \`${c.name}\` @ ${c.domain}${c.path}`);
      }
      out.push('');
    }
  }
  out.push('');

  // Storage Changes
  out.push('## Storage Changes');
  out.push('');
  appendStorageSection(out, 'localStorage', storageDiff.localStorage, opts);
  appendStorageSection(out, 'sessionStorage', storageDiff.sessionStorage, opts);
  out.push('');

  // Redirect Flow
  out.push('## Redirect Flow');
  out.push('');
  if (flow.redirects.length === 0) {
    out.push('_No redirects observed._');
  } else {
    for (const r of flow.redirects) {
      out.push(`- ${r.status}: ${r.fromUrl} → ${r.toUrl}`);
    }
  }
  out.push('');

  // Mermaid Diagram
  out.push('## Mermaid Diagram');
  out.push('');
  out.push('```mermaid');
  out.push(generateMermaidDiagram(flow));
  out.push('```');
  out.push('');

  // Timeline
  out.push('## Timeline');
  out.push('');
  if (flow.steps.length === 0) {
    out.push('_No timeline events._');
  } else {
    for (const step of flow.steps) {
      out.push(`${step.index + 1}. **${step.event.type}** — ${step.description}`);
    }
  }
  out.push('');

  // Security Notes
  out.push('## Security Notes');
  out.push('');
  if (flow.summary && flow.summary.warnings.length > 0) {
    for (const w of flow.summary.warnings) {
      out.push(`- _${w.level}_: ${w.message}`);
    }
  } else {
    out.push('No specific security notes raised for this capture.');
  }
  out.push('');
  out.push(
    `> ${TOOL_NAME} is intended for authorized systems only. Review this report before sharing.`,
  );
  out.push('');

  return out.join('\n');
}

function cookieValueDisplay(
  value: { masked: string; raw?: string },
  opts: MarkdownOptions,
): string {
  if (opts.includeRaw && !opts.enforceMasking && value.raw) {
    return '`' + value.raw + '`';
  }
  return '`' + value.masked + '`';
}

function flagSuffix(c: {
  httpOnly: boolean;
  secure: boolean;
  sameSite?: string;
}): string {
  const flags: string[] = [];
  if (c.httpOnly) flags.push('HttpOnly');
  if (c.secure) flags.push('Secure');
  if (c.sameSite) flags.push(`SameSite=${c.sameSite}`);
  return flags.length > 0 ? `_(${flags.join(', ')})_` : '';
}

function appendStorageSection(
  out: string[],
  title: string,
  diff: StorageDiff['localStorage'],
  opts: MarkdownOptions,
) {
  out.push(`### ${title}`);
  out.push('');
  if (diff.added.length === 0 && diff.changed.length === 0 && diff.removed.length === 0) {
    out.push('_No changes._');
    out.push('');
    return;
  }
  if (diff.added.length > 0) {
    out.push('**Added:**');
    for (const e of diff.added) {
      out.push(`- \`${e.key}\` = \`${displayValue(e.value, opts)}\``);
    }
    out.push('');
  }
  if (diff.changed.length > 0) {
    out.push('**Changed:**');
    for (const e of diff.changed) {
      out.push(`- \`${e.after.key}\``);
    }
    out.push('');
  }
  if (diff.removed.length > 0) {
    out.push('**Removed:**');
    for (const e of diff.removed) {
      out.push(`- \`${e.key}\``);
    }
    out.push('');
  }
}

function displayValue(
  value: { masked: string; raw?: string },
  opts: MarkdownOptions,
): string {
  if (opts.includeRaw && !opts.enforceMasking && value.raw) return value.raw;
  return value.masked;
}
