import { TOOL_NAME, TOOL_VERSION, SCHEMA_VERSION } from '@/core';
import type { AuthEvent, AuthFlow, CookieDiff, StorageDiff } from '@/core';
import {
  findJwts,
  findOAuthFlow,
  isNoteworthyEvent,
  type JwtLocation,
} from '@/analyzer';
import { generateMermaidDiagram } from './mermaid.js';

export type MarkdownOptions = {
  /** raw 민감 정보를 포함할지 여부. 기본 false. */
  includeRaw?: boolean;
  /** 헤더에 raw 토큰을 절대 포함하지 않음 (강제). */
  enforceMasking?: boolean;
  /**
   * "Highlights only" mode. 기본 true.
   *
   * - Timeline: noteworthy AuthEvent 만 표시
   * - Cookie Changes: HttpOnly 거나 session/auth/token/csrf 같은 이름 패턴인 쿠키만
   * - Storage Changes: token/auth/session/jwt 가 키에 포함된 항목만
   * - Redirect Flow: cross-domain redirect 만
   *
   * false면 모든 항목을 그대로 노출.
   */
  compact?: boolean;
  /** @deprecated `compact`를 사용하세요. */
  compactTimeline?: boolean;
};

const AUTH_COOKIE_PATTERN = /session|auth|token|csrf|xsrf|jwt/i;
const AUTH_STORAGE_KEY_PATTERN = /token|auth|session|jwt/i;

function isNoteworthyCookieName(name: string, httpOnly: boolean): boolean {
  return httpOnly || AUTH_COOKIE_PATTERN.test(name);
}
function isNoteworthyStorageKey(key: string): boolean {
  return AUTH_STORAGE_KEY_PATTERN.test(key);
}

/**
 * 리포트에 들어가는 라벨/제목 모음.
 * UI는 i18n에서 채워 주입하고, 라이브러리 사용자(CLI 등)는 기본 영어를 그대로 쓸 수 있다.
 *
 * 동적 보간이 필요한 항목(`formatConfidence`)만 함수, 나머지는 정적 문자열.
 */
export type ReportStrings = {
  title: string;
  disclaimer: string;
  summaryHeading: string;
  labelTarget: string;
  labelStarted: string;
  labelEnded: string;
  labelRequestsCaptured: string;
  labelLoginCandidates: string;
  authTypeHeading: string;
  labelAuthType: string;
  noSummary: string;
  /** `(confidence: X – high)` 형태로 들어가는 부분만 반환. */
  formatConfidence: (score: string, level: string) => string;
  signalsLabel: string;
  loginCandidateHeading: string;
  labelScore: string;
  labelMethodUrl: string;
  reasonsLabel: string;
  noLoginCandidate1: string;
  noLoginCandidate2: string;
  cookieHeading: string;
  noCookieChanges: string;
  addedLabel: string;
  changedLabel: string;
  removedLabel: string;
  storageHeading: string;
  noStorageChanges: string;
  redirectHeading: string;
  noRedirects: string;
  diagramHeading: string;
  timelineHeading: string;
  noTimeline: string;
  securityHeading: string;
  noSecurityNotes: string;
  footer: string;
  jwtHeading: string;
  jwtSourceLabels: Record<JwtLocation['source'], string>;
  jwtAlgorithm: string;
  jwtSubject: string;
  jwtIssuer: string;
  jwtAudience: string;
  jwtIssuedAt: string;
  jwtExpiresAt: string;
  jwtExpired: string;
  jwtNotExpired: string;
  jwtHeader: string;
  jwtPayload: string;
  jwtSignaturePreview: string;
  oauthHeading: string;
  oauthAuthorizeHeading: string;
  oauthTokenHeading: string;
  oauthResponseType: string;
  oauthClientId: string;
  oauthRedirectUri: string;
  oauthScopeRequested: string;
  oauthScopeGranted: string;
  oauthState: string;
  oauthNonce: string;
  oauthPkce: string;
  oauthPkceYes: string;
  oauthPkceNo: string;
  oauthGrantType: string;
  oauthTokenType: string;
  oauthExpiresIn: string;
  oauthExpiresAt: string;
  oauthRefreshToken: string;
  oauthIdToken: string;
  oauthYes: string;
  oauthNo: string;
};

export const DEFAULT_REPORT_STRINGS: ReportStrings = {
  title: `${TOOL_NAME} Report`,
  disclaimer: `Generated by ${TOOL_NAME} v${TOOL_VERSION} (schema ${SCHEMA_VERSION}). Sensitive values are masked by default.`,
  summaryHeading: 'Summary',
  labelTarget: 'Target URL',
  labelStarted: 'Started',
  labelEnded: 'Ended',
  labelRequestsCaptured: 'Requests captured',
  labelLoginCandidates: 'Login candidates',
  authTypeHeading: 'Detected Authentication Type',
  labelAuthType: 'Auth Type',
  noSummary: 'No summary available.',
  formatConfidence: (score, level) => `confidence: ${score} – ${level}`,
  signalsLabel: 'Signals:',
  loginCandidateHeading: 'Login Request Candidate',
  labelScore: 'Score',
  labelMethodUrl: 'Method/URL',
  reasonsLabel: 'Reasons:',
  noLoginCandidate1: 'No clear authentication request was detected.',
  noLoginCandidate2: 'You can manually select a request from the timeline.',
  cookieHeading: 'Cookie Changes',
  noCookieChanges: 'No cookie changes were detected during this capture.',
  addedLabel: 'Added:',
  changedLabel: 'Changed:',
  removedLabel: 'Removed:',
  storageHeading: 'Storage Changes',
  noStorageChanges: 'No changes.',
  redirectHeading: 'Redirect Flow',
  noRedirects: 'No redirects observed.',
  diagramHeading: 'Mermaid Diagram',
  timelineHeading: 'Timeline',
  noTimeline: 'No timeline events.',
  securityHeading: 'Security Notes',
  noSecurityNotes: 'No specific security notes raised for this capture.',
  footer: `${TOOL_NAME} is intended for authorized systems only. Review this report before sharing.`,
  jwtHeading: 'Decoded JWT tokens',
  jwtSourceLabels: {
    'request-header': 'Request header',
    'response-header': 'Response header',
    'response-body': 'Response body',
    cookie: 'Cookie',
    'storage-local': 'localStorage',
    'storage-session': 'sessionStorage',
  },
  jwtAlgorithm: 'Algorithm',
  jwtSubject: 'Subject (sub)',
  jwtIssuer: 'Issuer (iss)',
  jwtAudience: 'Audience (aud)',
  jwtIssuedAt: 'Issued at (iat)',
  jwtExpiresAt: 'Expires (exp)',
  jwtExpired: 'expired',
  jwtNotExpired: 'valid',
  jwtHeader: 'Header',
  jwtPayload: 'Payload',
  jwtSignaturePreview: 'Signature (masked)',
  oauthHeading: 'OAuth / OIDC flow',
  oauthAuthorizeHeading: 'Authorization request',
  oauthTokenHeading: 'Token exchange',
  oauthResponseType: 'response_type',
  oauthClientId: 'client_id',
  oauthRedirectUri: 'redirect_uri',
  oauthScopeRequested: 'Scope requested',
  oauthScopeGranted: 'Scope granted',
  oauthState: 'state',
  oauthNonce: 'nonce (OIDC)',
  oauthPkce: 'PKCE',
  oauthPkceYes: 'enabled',
  oauthPkceNo: 'not used',
  oauthGrantType: 'grant_type',
  oauthTokenType: 'token_type',
  oauthExpiresIn: 'expires_in',
  oauthExpiresAt: 'Expires at',
  oauthRefreshToken: 'refresh_token issued',
  oauthIdToken: 'id_token issued (OIDC)',
  oauthYes: 'yes',
  oauthNo: 'no',
};

export function generateMarkdownReport(
  flow: AuthFlow,
  cookieDiff: CookieDiff,
  storageDiff: StorageDiff,
  opts: MarkdownOptions = {},
  strings: ReportStrings = DEFAULT_REPORT_STRINGS,
): string {
  const s = strings;
  // Resolve compact mode. Default true. Honor legacy `compactTimeline`.
  const compact =
    opts.compact !== undefined
      ? opts.compact
      : opts.compactTimeline !== undefined
        ? opts.compactTimeline
        : true;
  const out: string[] = [];
  out.push(`# ${s.title}`);
  out.push('');
  out.push(`> ${s.disclaimer}`);
  out.push('');

  // Summary
  out.push(`## ${s.summaryHeading}`);
  out.push('');
  out.push(`- **${s.labelTarget}:** ${flow.targetUrl}`);
  out.push(`- **${s.labelStarted}:** ${flow.startedAt}`);
  if (flow.endedAt) out.push(`- **${s.labelEnded}:** ${flow.endedAt}`);
  out.push(`- **${s.labelRequestsCaptured}:** ${flow.requests.length}`);
  out.push(`- **${s.labelLoginCandidates}:** ${flow.loginCandidates.length}`);
  out.push('');

  // Auth Type
  out.push(`## ${s.authTypeHeading}`);
  out.push('');
  if (flow.summary) {
    out.push(
      `- **${s.labelAuthType}:** \`${flow.summary.authType}\` (${s.formatConfidence(flow.summary.confidence.toFixed(0), flow.summary.confidenceLevel)})`,
    );
    if (flow.summary.detectedSignals.length > 0) {
      out.push('');
      out.push(`**${s.signalsLabel}**`);
      out.push('');
      for (const sig of flow.summary.detectedSignals) {
        out.push(`- [+${sig.weight}] ${sig.description}`);
      }
    }
  } else {
    out.push(s.noSummary);
  }
  out.push('');

  // Login Candidate
  out.push(`## ${s.loginCandidateHeading}`);
  out.push('');
  const top = flow.loginCandidates[0];
  if (top) {
    const req = flow.requests.find((r) => r.id === top.requestId);
    out.push(`- **${s.labelScore}:** ${top.score} (${top.confidence})`);
    if (req) {
      out.push(`- **${s.labelMethodUrl}:** \`${req.method.toUpperCase()} ${req.url}\``);
    }
    out.push('');
    out.push(`**${s.reasonsLabel}**`);
    out.push('');
    for (const r of top.reasons) {
      out.push(`- ${r}`);
    }
  } else {
    out.push(s.noLoginCandidate1);
    out.push(s.noLoginCandidate2);
  }
  out.push('');

  // Cookie Changes — when compact, only HttpOnly or auth-shaped names.
  out.push(`## ${s.cookieHeading}`);
  out.push('');
  const cookieAdded = compact
    ? cookieDiff.added.filter((c) => isNoteworthyCookieName(c.name, c.httpOnly))
    : cookieDiff.added;
  const cookieChanged = compact
    ? cookieDiff.changed.filter((c) =>
        isNoteworthyCookieName(c.after.name, c.after.httpOnly),
      )
    : cookieDiff.changed;
  const cookieRemoved = compact
    ? cookieDiff.removed.filter((c) => isNoteworthyCookieName(c.name, c.httpOnly))
    : cookieDiff.removed;
  if (
    cookieAdded.length === 0 &&
    cookieRemoved.length === 0 &&
    cookieChanged.length === 0
  ) {
    out.push(s.noCookieChanges);
  } else {
    if (cookieAdded.length > 0) {
      out.push(`**${s.addedLabel}**`);
      out.push('');
      for (const c of cookieAdded) {
        out.push(
          `- \`${c.name}\` @ ${c.domain}${c.path} → ${cookieValueDisplay(c.value, opts)} ${flagSuffix(c)}`,
        );
      }
      out.push('');
    }
    if (cookieChanged.length > 0) {
      out.push(`**${s.changedLabel}**`);
      out.push('');
      for (const c of cookieChanged) {
        out.push(
          `- \`${c.after.name}\` @ ${c.after.domain}${c.after.path}: ${cookieValueDisplay(c.before.value, opts)} → ${cookieValueDisplay(c.after.value, opts)}`,
        );
      }
      out.push('');
    }
    if (cookieRemoved.length > 0) {
      out.push(`**${s.removedLabel}**`);
      out.push('');
      for (const c of cookieRemoved) {
        out.push(`- \`${c.name}\` @ ${c.domain}${c.path}`);
      }
      out.push('');
    }
  }
  if (compact) {
    const omitted =
      cookieDiff.added.length -
      cookieAdded.length +
      (cookieDiff.changed.length - cookieChanged.length) +
      (cookieDiff.removed.length - cookieRemoved.length);
    if (omitted > 0) out.push(`_+${omitted} non-auth cookie changes omitted._`);
  }
  out.push('');

  // Storage Changes — when compact, only token/auth-shaped keys.
  out.push(`## ${s.storageHeading}`);
  out.push('');
  const localStorageOmitted = appendStorageSection(
    out,
    'localStorage',
    storageDiff.localStorage,
    opts,
    s,
    compact,
  );
  const sessionStorageOmitted = appendStorageSection(
    out,
    'sessionStorage',
    storageDiff.sessionStorage,
    opts,
    s,
    compact,
  );
  if (compact && localStorageOmitted + sessionStorageOmitted > 0) {
    out.push(
      `_+${localStorageOmitted + sessionStorageOmitted} non-auth storage changes omitted._`,
    );
  }
  out.push('');

  // Redirect Flow — when compact, only cross-domain.
  out.push(`## ${s.redirectHeading}`);
  out.push('');
  const targetHost = (() => {
    try {
      return new URL(flow.targetUrl).host.toLowerCase();
    } catch {
      return '';
    }
  })();
  const isCrossDomain = (from: string, to: string) => {
    try {
      const fh = new URL(from).host.toLowerCase();
      const th = new URL(to).host.toLowerCase();
      return fh !== th || (targetHost ? th !== targetHost : false);
    } catch {
      return false;
    }
  };
  const shownRedirects = compact
    ? flow.redirects.filter((r) => isCrossDomain(r.fromUrl, r.toUrl))
    : flow.redirects;
  if (shownRedirects.length === 0) {
    out.push(`_${s.noRedirects}_`);
  } else {
    for (const r of shownRedirects) {
      out.push(`- ${r.status}: ${r.fromUrl} → ${r.toUrl}`);
    }
  }
  if (compact && flow.redirects.length > shownRedirects.length) {
    out.push('');
    out.push(
      `_+${flow.redirects.length - shownRedirects.length} same-domain redirects omitted._`,
    );
  }
  out.push('');

  // Mermaid Diagram
  out.push(`## ${s.diagramHeading}`);
  out.push('');
  out.push('```mermaid');
  out.push(generateMermaidDiagram(flow));
  out.push('```');
  out.push('');

  // Timeline (compact by default — only noteworthy auth events).
  out.push(`## ${s.timelineHeading}`);
  out.push('');
  const shownSteps = compact
    ? flow.steps.filter((step) => isNoteworthyEvent(step.event as AuthEvent, step.index))
    : flow.steps;
  if (shownSteps.length === 0) {
    out.push(`_${s.noTimeline}_`);
  } else {
    let n = 0;
    for (const step of shownSteps) {
      n += 1;
      out.push(`${n}. **${step.event.type}** — ${step.description}`);
    }
    if (compact && flow.steps.length > shownSteps.length) {
      out.push('');
      out.push(`_+${flow.steps.length - shownSteps.length} additional events omitted._`);
    }
  }
  out.push('');

  // OAuth / OIDC — only render if authorize or token endpoint observed.
  const oauth = findOAuthFlow(flow);
  if (oauth.authorizeRequests.length > 0 || oauth.tokenExchanges.length > 0) {
    out.push(`## ${s.oauthHeading}`);
    out.push('');
    for (const a of oauth.authorizeRequests) {
      out.push(`### ${s.oauthAuthorizeHeading} — \`${a.endpoint}\``);
      out.push('');
      if (a.responseType) out.push(`- **${s.oauthResponseType}:** \`${a.responseType}\``);
      if (a.clientId) out.push(`- **${s.oauthClientId}:** \`${a.clientId}\``);
      if (a.redirectUri) out.push(`- **${s.oauthRedirectUri}:** \`${a.redirectUri}\``);
      if (a.scope) out.push(`- **${s.oauthScopeRequested}:** \`${a.scope}\``);
      if (a.state) out.push(`- **${s.oauthState}:** \`${a.state}\``);
      if (a.nonce) out.push(`- **${s.oauthNonce}:** \`${a.nonce}\``);
      out.push(
        `- **${s.oauthPkce}:** ${a.pkce ? s.oauthPkceYes : s.oauthPkceNo}${a.codeChallengeMethod ? ` (\`${a.codeChallengeMethod}\`)` : ''}`,
      );
      out.push('');
    }
    for (const e of oauth.tokenExchanges) {
      out.push(`### ${s.oauthTokenHeading} — \`${e.endpoint}\``);
      out.push('');
      if (e.grantType) out.push(`- **${s.oauthGrantType}:** \`${e.grantType}\``);
      if (e.clientId) out.push(`- **${s.oauthClientId}:** \`${e.clientId}\``);
      if (e.tokenType) out.push(`- **${s.oauthTokenType}:** \`${e.tokenType}\``);
      if (e.scope) out.push(`- **${s.oauthScopeGranted}:** \`${e.scope}\``);
      if (e.expiresInSeconds !== undefined) {
        out.push(`- **${s.oauthExpiresIn}:** \`${e.expiresInSeconds}s\``);
      }
      if (e.expiresAt) {
        out.push(`- **${s.oauthExpiresAt}:** ${e.expiresAt.toISOString()}`);
      }
      out.push(`- **${s.oauthRefreshToken}:** ${e.hasRefreshToken ? s.oauthYes : s.oauthNo}`);
      out.push(`- **${s.oauthIdToken}:** ${e.hasIdToken ? s.oauthYes : s.oauthNo}`);
      out.push('');
    }
  }

  // Decoded JWTs — only render section if any tokens were found.
  const jwts = findJwts(flow);
  if (jwts.length > 0) {
    out.push(`## ${s.jwtHeading}`);
    out.push('');
    for (const j of jwts) {
      out.push(`### ${s.jwtSourceLabels[j.source]} — \`${j.label}\``);
      out.push('');
      const claims: string[] = [];
      if (j.decoded.algorithm) claims.push(`- **${s.jwtAlgorithm}:** \`${j.decoded.algorithm}\``);
      if (typeof j.decoded.payload.sub === 'string')
        claims.push(`- **${s.jwtSubject}:** \`${j.decoded.payload.sub}\``);
      if (typeof j.decoded.payload.iss === 'string')
        claims.push(`- **${s.jwtIssuer}:** \`${j.decoded.payload.iss}\``);
      if (j.decoded.payload.aud !== undefined)
        claims.push(`- **${s.jwtAudience}:** \`${JSON.stringify(j.decoded.payload.aud)}\``);
      if (j.decoded.issuedAt)
        claims.push(`- **${s.jwtIssuedAt}:** ${j.decoded.issuedAt.toISOString()}`);
      if (j.decoded.expiresAt) {
        const status = j.decoded.expired ? s.jwtExpired : s.jwtNotExpired;
        claims.push(
          `- **${s.jwtExpiresAt}:** ${j.decoded.expiresAt.toISOString()} _(${status})_`,
        );
      }
      claims.push(`- **${s.jwtSignaturePreview}:** \`${j.decoded.signaturePreview}\``);
      for (const line of claims) out.push(line);
      out.push('');
      out.push(`**${s.jwtHeader}:**`);
      out.push('');
      out.push('```json');
      out.push(JSON.stringify(j.decoded.header, null, 2));
      out.push('```');
      out.push('');
      out.push(`**${s.jwtPayload}:**`);
      out.push('');
      out.push('```json');
      out.push(JSON.stringify(j.decoded.payload, null, 2));
      out.push('```');
      out.push('');
    }
  }

  // Security Notes
  out.push(`## ${s.securityHeading}`);
  out.push('');
  if (flow.summary && flow.summary.warnings.length > 0) {
    for (const w of flow.summary.warnings) {
      out.push(`- _${w.level}_: ${w.message}`);
    }
  } else {
    out.push(s.noSecurityNotes);
  }
  out.push('');
  out.push(`> ${s.footer}`);
  out.push('');

  return out.join('\n');
}

function cookieValueDisplay(
  value: { masked: string; raw?: string },
  opts: MarkdownOptions,
): string {
  if (opts.includeRaw && !opts.enforceMasking && value.raw) {
    return '`' + value.raw + '`';
  }
  return '`' + value.masked + '`';
}

function flagSuffix(c: {
  httpOnly: boolean;
  secure: boolean;
  sameSite?: string;
}): string {
  const flags: string[] = [];
  if (c.httpOnly) flags.push('HttpOnly');
  if (c.secure) flags.push('Secure');
  if (c.sameSite) flags.push(`SameSite=${c.sameSite}`);
  return flags.length > 0 ? `_(${flags.join(', ')})_` : '';
}

function appendStorageSection(
  out: string[],
  title: string,
  diff: StorageDiff['localStorage'],
  opts: MarkdownOptions,
  s: ReportStrings,
  compact: boolean,
): number {
  out.push(`### ${title}`);
  out.push('');
  const added = compact ? diff.added.filter((e) => isNoteworthyStorageKey(e.key)) : diff.added;
  const changed = compact
    ? diff.changed.filter((e) => isNoteworthyStorageKey(e.after.key))
    : diff.changed;
  const removed = compact ? diff.removed.filter((e) => isNoteworthyStorageKey(e.key)) : diff.removed;
  const omitted =
    diff.added.length -
    added.length +
    (diff.changed.length - changed.length) +
    (diff.removed.length - removed.length);
  if (added.length === 0 && changed.length === 0 && removed.length === 0) {
    out.push(`_${s.noStorageChanges}_`);
    out.push('');
    return omitted;
  }
  if (added.length > 0) {
    out.push(`**${s.addedLabel}**`);
    for (const e of added) {
      out.push(`- \`${e.key}\` = \`${displayValue(e.value, opts)}\``);
    }
    out.push('');
  }
  if (changed.length > 0) {
    out.push(`**${s.changedLabel}**`);
    for (const e of changed) {
      out.push(`- \`${e.after.key}\``);
    }
    out.push('');
  }
  if (removed.length > 0) {
    out.push(`**${s.removedLabel}**`);
    for (const e of removed) {
      out.push(`- \`${e.key}\``);
    }
    out.push('');
  }
  return omitted;
}

function displayValue(
  value: { masked: string; raw?: string },
  opts: MarkdownOptions,
): string {
  if (opts.includeRaw && !opts.enforceMasking && value.raw) return value.raw;
  return value.masked;
}
