/**
 * Postman Collection v2.1 generator.
 *
 * 캡처된 인증 흐름의 각 요청을 Postman item으로 변환한다. 사용자가 외부 도구
 * (Postman/Insomnia)에서 인증된 API 표면을 즉시 탐색·테스트할 수 있게.
 *
 * 민감 헤더 처리는 `MarkdownOptions.includeRaw`와 동일한 정책 — 기본 마스킹.
 */

import { SCHEMA_VERSION, TOOL_NAME, TOOL_VERSION } from '@/core';
import type { AuthFlow, RequestRecord } from '@/core';

export type PostmanOptions = {
  /** 컬렉션에 포함시킬 요청 ID 목록. 미지정 시 모든 요청. */
  requestIds?: string[];
  /** raw 헤더/바디 포함 여부 (기본 false → 마스킹된 값). */
  includeRaw?: boolean;
  /** 컬렉션 이름 (기본: `AuthLens — <targetUrl>`) */
  name?: string;
};

type PostmanItem = {
  name: string;
  request: {
    method: string;
    header: Array<{ key: string; value: string; type: 'text' }>;
    url: {
      raw: string;
      protocol?: string;
      host?: string[];
      path?: string[];
      query?: Array<{ key: string; value: string }>;
    };
    body?: { mode: 'raw' | 'urlencoded'; raw?: string; urlencoded?: Array<{ key: string; value: string }> };
  };
  response: [];
};

export type PostmanCollection = {
  info: {
    name: string;
    schema: string;
    _postman_id?: string;
    description?: string;
  };
  item: PostmanItem[];
};

export function generatePostmanCollection(
  flow: AuthFlow,
  opts: PostmanOptions = {},
): PostmanCollection {
  const filter = opts.requestIds ? new Set(opts.requestIds) : undefined;
  const items: PostmanItem[] = flow.requests
    .filter((r) => (filter ? filter.has(r.id) : true))
    .map((r) => requestToItem(r, opts));

  return {
    info: {
      name: opts.name ?? `${TOOL_NAME} — ${flow.targetUrl}`,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
      description:
        `Captured ${flow.requests.length} requests on ${flow.targetUrl}.\n` +
        `Generated by ${TOOL_NAME} v${TOOL_VERSION} (schema ${SCHEMA_VERSION}).\n` +
        `Sensitive values ${opts.includeRaw ? 'INCLUDED RAW' : 'are masked'}.`,
    },
    item: items,
  };
}

export function stringifyPostmanCollection(
  flow: AuthFlow,
  opts: PostmanOptions = {},
  indent = 2,
): string {
  return JSON.stringify(generatePostmanCollection(flow, opts), null, indent);
}

function requestToItem(req: RequestRecord, opts: PostmanOptions): PostmanItem {
  const includeRaw = opts.includeRaw === true;
  let u: URL | undefined;
  try {
    u = new URL(req.url);
  } catch {
    /* keep undefined */
  }
  const headers = Object.entries(req.headers).map(([key, v]) => ({
    key,
    value: includeRaw && v.raw ? v.raw : v.masked,
    type: 'text' as const,
  }));
  const item: PostmanItem = {
    name: `${req.method.toUpperCase()} ${u ? u.pathname : req.url}`,
    request: {
      method: req.method.toUpperCase(),
      header: headers,
      url: u
        ? {
            raw: req.url,
            protocol: u.protocol.replace(':', ''),
            host: u.host.split('.'),
            path: u.pathname.split('/').filter(Boolean),
            query: Array.from(u.searchParams.entries()).map(([key, value]) => ({ key, value })),
          }
        : { raw: req.url },
    },
    response: [],
  };
  if (req.postData) {
    const bodyText = includeRaw && req.postData.raw ? req.postData.raw : req.postData.masked;
    item.request.body = { mode: 'raw', raw: bodyText };
  }
  return item;
}
